# **Datasets Management**

# Import Relevant Libraries

In [1]:
# Import standard libraries for file and directory operations
import os
import fnmatch
import shutil

# Import data manipulation libraries
import pandas as pd  # Pandas for handling data in tabular form
import numpy as np   # NumPy for numerical operations

# Import a third-party library for natural sorting
from natsort import natsorted  # natsort for natural sorting of strings

# First Organization

Create a list of all directories.

In [2]:
# Get the current working directory
current_directory = os.getcwd()

# List all directories in the current directory
directories = [d for d in os.listdir(current_directory)
               if os.path.isdir(os.path.join(current_directory, d))]

# Display the number of folders in the current directory
print(f"There are {len(directories)} folders in the current directory, which are:")
print()

# Print each directory name on a new line
for dir in directories:
    print(dir)

There are 4 folders in the current directory, which are:

Questionnaire Data
Examination Data
Laboratory Data
Demographic Variables and Sample Weights

Remove the "All datastest" folder from the list of folders in the current directory.

In [3]:
# Check if "All Datasets" is in the list of directories and remove it
if "All Datasets" in directories:
    directories.remove("All Datasets")

# Display the remaining directories after the potential removal
# Print each directory name on a new line
for dir in directories:
    print(dir)

Questionnaire Data
Examination Data
Laboratory Data
Demographic Variables and Sample Weights

It seems nice. Now create a list of xpt files' paths in the current directory.

In [4]:
def find_xpt_files(root_dir):
    """
    Find .XPT files in a directory and its subdirectories.

    Parameters:
    - root_dir (str): The root directory to start searching for .XPT files.

    Returns:
    - List[str]: A list of full paths to .XPT files found in the specified directory and its subdirectories.
    """

    # Initialize an empty list to store the file paths
    xpt_files = []

    for root, dirs, files in os.walk(root_dir):
        # Walk through the directory tree rooted at root_dir.
        for filename in fnmatch.filter(files, "*.XPT"):
            # For each file with a .XPT extension, add its full path to the xpt_files list.
            xpt_files.append(os.path.join(root, filename))

    return xpt_files

In [5]:
# Specify the current directory as the root directory.
current_directory = os.getcwd()

# Call the find_xpt_files function with the current directory.
xpt_file_paths = find_xpt_files(current_directory)

# Print each found .XPT file path on a new line.
for xpt_file_path in xpt_file_paths:
    print(xpt_file_path)

/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Questionnaire Data/Diabetes/DIQ_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Examination Data/Blood Pressure/BPX_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Examination Data/Body Measures/BMX_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Laboratory Data/Glycohemoglobin/GHB_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Laboratory Data/Cholesterol - Total/TCHOL_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Laboratory Data/Plasma Fasting Glucose & Insulin/GLU_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Laboratory Data/Oral Glucose Tolerance Test/OGTT_G.XPT
/Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/Demographic Variables and Sample Weights/DEMO_G.XPT

Create a new directory to save all datasets in it.

In [6]:
# Define the name of the new folder.
new_folder_name = "All Datasets"

# Create the full path to the new folder.
new_folder_path = os.path.join(current_directory, new_folder_name)

# Create the new folder if it doesn't exist.
os.makedirs(new_folder_path, exist_ok=True)

Now, create a copy for each dataset in a new directory.

In [7]:
# Check if "All Datasets" folder is empty.
all_datasets_path = os.path.join(current_directory, "All Datasets")

if not os.listdir(all_datasets_path):
    # Loop through each .XPT file in the list.
    for xpt_file_path in xpt_file_paths:

        # Extract the filename from the full path.
        filename = os.path.basename(xpt_file_path)

        # Determine the subdirectories between the current directory and the file.
        subdirectories = os.path.relpath(xpt_file_path, current_directory).split(os.path.sep)[:-1]

        # Generate a subdirectory name by joining the subdirectories with underscores.
        subdirectory_name = "_".join(subdirectories)

        # Remove spaces from the subdirectory name.
        subdirectory_name = subdirectory_name.replace(" ", "")

        # Construct the new filename with the subdirectory name and .XPT extension.
        new_filename = f"{subdirectory_name}" + ".XPT"

        # Create the full path to the new location for the file within the new folder.
        new_file_path = os.path.join(all_datasets_path, new_filename)

        # Copy the .XPT file to the new location.
        shutil.copy(xpt_file_path, new_file_path)

    print(f"Files copied to: {all_datasets_path}")
else:
    print("The 'All Datasets' folder is not empty. No files were copied.")

Files copied to: /Users/shahriyar/Desktop/Study/SUT/Opartions Analytics/Final Project/Datasets/2011-2012/All Datasets

Seems perfect. Now, we can read these files.</br>
Although it does not seem a good idea, read all of the files in the memory.

In [8]:
dataset_dict = {}

# Call the find_xpt_files function to obtain a list of XPT file paths within the specified directory.
xpt_file_paths = find_xpt_files(new_folder_path)

# Loop through each XPT file path to read it.
for xpt_file_path in xpt_file_paths:

    dataset_name = os.path.basename(xpt_file_path).split(".XPT")[0]
    dataset_dict[dataset_name] = pd.read_sas(xpt_file_path, format="xport")
    
# Iterate through each dataset in the dictionary to show their information.
for key in dataset_dict.keys():

    print(key)
    print(dataset_dict[key].shape)
    print()

QuestionnaireData_Diabetes
(9364, 53)

LaboratoryData_OralGlucoseToleranceTest
(2815, 12)

ExaminationData_BloodPressure
(9338, 27)

LaboratoryData_PlasmaFastingGlucose&Insulin
(3239, 8)

LaboratoryData_Cholesterol-Total
(7821, 3)

ExaminationData_BodyMeasures
(9338, 26)

LaboratoryData_Glycohemoglobin
(6549, 2)

DemographicVariablesandSampleWeights
(9756, 48)

# Extract All The Important Features

***Guide***

- <font color='grey'>*General Features*</font>
- <font color='red'>*ADA Biomarker Criteria*</font>
- <font color='yellow'>*ADA Screening Guideline*</font>

### **Features**

- **DemographicVariablesandSampleWeights**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: grey; font-size: 200%;">&bull;</span> RIAGENDR - Gender</br>
    <span style="color: grey; font-size: 200%;">&bull;</span> RIDAGEYR - Age at Screening Adjudicated</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> RIDRETH1 - Race/Ethnicity

- **ExaminationData_BodyMeasures**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> BMXBMI - Body Mass Index (kg/m**2)

- **ExaminationData_BloodPressure**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> BPXSY1 - Systolic: Blood pres (1st rdg) mm Hg</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> BPXDI1 - Diastolic: Blood pres (1st rdg) mm Hg</br>

- **LaboratoryData_Cholesterol-Total**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> LBXTC - Total cholesterol (mg/dL)

- **LaboratoryData_Glycohemoglobin**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: red; font-size: 200%;">&bull;</span> LBXGH - Glycohemoglobin/HbA1C (%)

- **LaboratoryData_OralGlucoseToleranceTest**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: red; font-size: 200%;">&bull;</span> LBXGLT - Two Hour Glucose/2hrPG (mg/dL)

- **LaboratoryData_PlasmaFastingGlucose&Insulin**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: red; font-size: 200%;">&bull;</span> LBXGLU - Fasting Glucose/FPG (mg/dL)

- **QuestionnaireData_Blood Pressure & Cholesterol**

    <span style="color: yellow; font-size: 200%;">&bull;</span> BPQ020 - Ever told you had high blood pressure/Hypertension

- **QuestionnaireData_Diabetes**

    <span style="color: grey; font-size: 200%;">&bull;</span> SEQN - Respondent sequence number</br>
    <span style="color: yellow; font-size: 200%;">&bull;</span> DIQ170 - Ever told have health risk for diabetes</br>

Firts of all, create a dictionary of all the important features for datasets.

In [9]:
features_dict = {
    "DemographicVariablesandSampleWeights" :
        ["SEQN",
         "RIAGENDR",
         "RIDAGEYR",
         "RIDRETH1"],
    "ExaminationData_BodyMeasures" :
        ["SEQN",
         "BMXBMI"],
    "ExaminationData_BloodPressure" :
        ["SEQN",
         "BPXSY1",
         "BPXDI1"],
    "LaboratoryData_PlasmaFastingGlucose&Insulin" :
        ["SEQN",
         "LBXGLU"],
    "LaboratoryData_OralGlucoseToleranceTest" :
        ["SEQN",
         "LBXGLT"],
    "LaboratoryData_Glycohemoglobin" :
        ["SEQN",
         "LBXGH"],
    "LaboratoryData_Cholesterol-Total" :
        ["SEQN",
         "LBXTC"],
    "QuestionnaireData_Diabetes" :
        ["SEQN",
         "DIQ170"]
        }

Now, we can delete the irrelevant features.

In [10]:
# Iterate through the keys in the dataset_dict (each key represents a dataset).
for key in dataset_dict.keys():
    
    # Get the DataFrame associated with the current dataset.
    df = dataset_dict[key]

    # Get the list of relevant features for th
    # is dataset from the features_dict.
    relevant_features = features_dict[key]

    # Create a new DataFrame containing only the relevant features.
    new_df = df[relevant_features]

    # Update the dataset_dict with the new DataFrame, containing only relevant features.
    dataset_dict[key] = new_df

Now, let's check not missing values for each dataset's features.

In [11]:
# Iterate through the keys in dataset_dict, sorted in alphabetical order.
for key in sorted(list(dataset_dict.keys())):
        
    # Get the DataFrame associated with the current key.
    df = dataset_dict[key]    
    
    # Print the dataset key.
    print(key)
    print()
    
    # Calculate the proportion of non-missing values for each feature in the DataFrame.
    # This is done by dividing the count of non-null values by the total number of rows and multiplying by 100.
    proportions = round(((df.count() / len(df)) * 100), 2)
    
    # Print the proportions of non-missing values for each feature in the DataFrame.
    print(proportions)

    # Check if the current key is not the last key in the sorted list of keys.
    if key != sorted(list(dataset_dict.keys()))[-1]:
        print("-" * 80)

DemographicVariablesandSampleWeights

SEQN        100.0
RIAGENDR    100.0
RIDAGEYR    100.0
RIDRETH1    100.0
dtype: float64
--------------------------------------------------------------------------------
ExaminationData_BloodPressure

SEQN      100.00
BPXSY1     72.35
BPXDI1     72.35
dtype: float64
--------------------------------------------------------------------------------
ExaminationData_BodyMeasures

SEQN      100.00
BMXBMI     92.12
dtype: float64
--------------------------------------------------------------------------------
LaboratoryData_Cholesterol-Total

SEQN     100.00
LBXTC     89.35
dtype: float64
--------------------------------------------------------------------------------
LaboratoryData_Glycohemoglobin

SEQN     100.00
LBXGH     93.83
dtype: float64
--------------------------------------------------------------------------------
LaboratoryData_OralGlucoseToleranceTest

SEQN      100.00
LBXGLT     81.24
dtype: float64
--------------------------------------------------------------------------------
LaboratoryData_PlasmaFastingGlucose&Insulin

SEQN      100.00
LBXGLU     93.64
dtype: float64
--------------------------------------------------------------------------------
QuestionnaireData_Diabetes

SEQN      100.0
DIQ170     65.4
dtype: float64

# Merge The Datasets

Outer-merge the datasets by the key of SEQN.

In [12]:
# Create an empty DataFrame with 'SEQN' column
merged_df = pd.DataFrame({"SEQN": dataset_dict[list(dataset_dict.keys())[0]]["SEQN"]})

# Iterate through the DataFrames in dataset_dict and merge them into merged_df based on the 'SEQN' column using an outer join.
for df in dataset_dict.values():
    merged_df = pd.merge(merged_df, df, on="SEQN", how="inner")

print("Dataset has the shape of:", merged_df.shape)
merged_df.head(5)

Dataset has the shape of: (2815, 12)

,SEQN,DIQ170,LBXGLT,BPXSY1,BPXDI1,LBXGLU,LBXTC,BMXBMI,LBXGH,RIAGENDR,RIDAGEYR,RIDRETH1
0,62161.0,2.0,110.0,110.0,82.0,92.0,168.0,23.3,5.1,1.0,22.0,3.0
1,62164.0,2.0,142.0,116.0,56.0,82.0,190.0,23.2,4.9,2.0,44.0,3.0
2,62165.0,2.0,112.0,110.0,64.0,88.0,161.0,27.2,5.9,2.0,14.0,4.0
3,62169.0,2.0,95.0,124.0,80.0,107.0,132.0,20.1,5.4,1.0,21.0,5.0
4,62171.0,2.0,110.0,112.0,54.0,93.0,118.0,19.9,5.0,1.0,14.0,1.0

Change the datast features' names in order to make the table more readable.</br>
But, before changing the dataset features' names change the sequence of the features.

In [13]:
# Initialize an empty list to store column names
columns = []

# Iterate through the keys of features_dict
for key in features_dict.keys():
    
    # Get the list of features associated with the current key
    features = features_dict[key]
    
    # Remove "SEQN" from the list of features
    features.remove("SEQN")
    
    # Add the remaining features to the columns list
    columns += features
    
# Add "SEQN" as the first column in the columns list
columns = ["SEQN"] + columns

In [14]:
# Filter the columns of merged_df based on the specified list of column names (columns)
merged_df = merged_df[columns]

# Reset the index of the DataFrame
merged_df.reset_index(inplace=True)

# Drop the old index column
merged_df.drop(columns="index", inplace=True)

# Print the shape of the resulting DataFrame
print("The dataset shape is: ", merged_df.shape)

# Display the first 5 rows of the DataFrame
merged_df.head(5)

The dataset shape is:  (2815, 12)

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH1,BMXBMI,BPXSY1,BPXDI1,LBXGLU,LBXGLT,LBXGH,LBXTC,DIQ170
0,62161.0,1.0,22.0,3.0,23.3,110.0,82.0,92.0,110.0,5.1,168.0,2.0
1,62164.0,2.0,44.0,3.0,23.2,116.0,56.0,82.0,142.0,4.9,190.0,2.0
2,62165.0,2.0,14.0,4.0,27.2,110.0,64.0,88.0,112.0,5.9,161.0,2.0
3,62169.0,1.0,21.0,5.0,20.1,124.0,80.0,107.0,95.0,5.4,132.0,2.0
4,62171.0,1.0,14.0,1.0,19.9,112.0,54.0,93.0,110.0,5.0,118.0,2.0

In [15]:
new_features_names = {
    "SEQN" : "ID",
    "RIAGENDR" : "Gender",
    "RIDAGEYR" : "Age",
    "RIDRETH1" : "Race",
    "BMXBMI" : "BMI",
    "BPXSY1" : "Systolic BP",
    "BPXDI1" : "Diastolic BP",
    "LBXGLU" : "FPG",
    "LBXGLT" : "2hrPG",
    "LBXGH" : "HbA1c",
    "LBXTC" : "Total Cholestrol",
    "DIQ170" : "Diabetes Risk",
    "BPQ020" : "Hypertension"
}

In [16]:
final_df = merged_df.rename(columns=new_features_names)

final_df.head(5)

,ID,Gender,Age,Race,BMI,Systolic BP,Diastolic BP,FPG,2hrPG,HbA1c,Total Cholestrol,Diabetes Risk
0,62161.0,1.0,22.0,3.0,23.3,110.0,82.0,92.0,110.0,5.1,168.0,2.0
1,62164.0,2.0,44.0,3.0,23.2,116.0,56.0,82.0,142.0,4.9,190.0,2.0
2,62165.0,2.0,14.0,4.0,27.2,110.0,64.0,88.0,112.0,5.9,161.0,2.0
3,62169.0,1.0,21.0,5.0,20.1,124.0,80.0,107.0,95.0,5.4,132.0,2.0
4,62171.0,1.0,14.0,1.0,19.9,112.0,54.0,93.0,110.0,5.0,118.0,2.0

# Check the Dataset Features' Data Types

First, make the discrete features' type integer.

In [17]:
# Define a custom rounding function that handles NaN values
def round_with_nan(x):
    if pd.notna(x):
        return int(round(x))
    return x

In [18]:
categorical_features = ["Gender", "Age", "Race", "Diabetes Risk"]

# Apply the custom rounding function to the specified columns
final_df[categorical_features] = final_df[categorical_features].applymap(round_with_nan)

final_df.head(5)

,ID,Gender,Age,Race,BMI,Systolic BP,Diastolic BP,FPG,2hrPG,HbA1c,Total Cholestrol,Diabetes Risk
0,62161.0,1,22,3,23.3,110.0,82.0,92.0,110.0,5.1,168.0,2.0
1,62164.0,2,44,3,23.2,116.0,56.0,82.0,142.0,4.9,190.0,2.0
2,62165.0,2,14,4,27.2,110.0,64.0,88.0,112.0,5.9,161.0,2.0
3,62169.0,1,21,5,20.1,124.0,80.0,107.0,95.0,5.4,132.0,2.0
4,62171.0,1,14,1,19.9,112.0,54.0,93.0,110.0,5.0,118.0,2.0

# Select the Patients with the Ages in the Range of 12 to 19

Based on the project scope, extract the records with the ages in the relevant range.

In [19]:
# Filter the DataFrame to include only rows where the "Age" column values are between 12 and 19 (inclusive)
final_df = final_df[(final_df["Age"] >= 12) & (final_df["Age"] <= 19)]

# Print the shape of the resulting DataFrame
print("The dataset shape is: ", final_df.shape)

# Display the first 5 rows of the DataFrame
final_df.head(5)

The dataset shape is:  (520, 12)

,ID,Gender,Age,Race,BMI,Systolic BP,Diastolic BP,FPG,2hrPG,HbA1c,Total Cholestrol,Diabetes Risk
2,62165.0,2,14,4,27.2,110.0,64.0,88.0,112.0,5.9,161.0,2.0
4,62171.0,1,14,1,19.9,112.0,54.0,93.0,110.0,5.0,118.0,2.0
10,62190.0,2,15,1,17.0,110.0,52.0,93.0,66.0,5.2,159.0,2.0
12,62193.0,1,17,4,28.5,136.0,70.0,104.0,139.0,5.6,135.0,2.0
19,62210.0,1,15,3,26.0,114.0,46.0,98.0,92.0,5.2,175.0,2.0

Save the final dataset.

In [20]:
final_df.to_csv("final_df_1112.csv",
                index=False)